app/views/confirmacion.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app import db, socketio
from app.models import Transacciones, Item
from app.decorators import roles_required
from datetime import datetime

confirmacion = Blueprint('confirmacion', __name__)

@confirmacion.route('/confirmacion/<int:tr_id>', methods=['GET', 'POST'])
@roles_required('admin', 'usuario')
@login_required
def confirmacion_view(tr_id):
    transaccion = Transacciones.query.get(tr_id)
    
    if not transaccion:
        return "Transaccion no encontrada", 404
    
    if request.method == 'POST':
        cantidad_entregada = request.form.get('cantidad_entregada')
        if not cantidad_entregada:
            return "Por favor ingrese la cantidad que fue entregada.", 400
        
        transaccion.cantidad_entregada = cantidad_entregada
        transaccion.confirmado = True
        transaccion.fecha_confirmado = datetime.utcnow()
        transaccion.confirmado_por_id = current_user.user_id
 
        item = Item.query.get(transaccion.item_id)
        item.cantidad -= int(cantidad_entregada)
        
        db.session.commit()

        socketio.emit('delivery_confirmed', {'message': 'Delivery confirmed'})


        return redirect(url_for('main.index'))
    
    return render_template('confirmacion.html', transaccion=transaccion)

@confirmacion.route('/confirmaciones')
@roles_required('admin', 'usuario')
@login_required
def confirmaciones_view():
    transacciones_pendientes = Transacciones.query.filter_by(confirmado=False).all()
    return render_template('confirmaciones.html', transacciones=transacciones_pendientes)


app/views/envios.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from app import db
from app.models import Transacciones
from app.decorators import roles_required
from datetime import datetime, timedelta

envios = Blueprint('envios', __name__)

@envios.route('/envios')
@login_required
@roles_required('principal', 'admin')
def envios_view():
    if current_user.rol not in ['admin', 'principal']:
        flash('No tienes acceso a esta página.', 'danger')
        return redirect(url_for('main.index'))

    today = datetime.today().date()
    transacciones = Transacciones.query.filter(
        Transacciones.tr_tipo == 'Pedido',
         Transacciones.confirmado == False,
        db.cast(Transacciones.fecha_pedido, db.Date) == today
    ).order_by(Transacciones.dept_id).all()
    
    return render_template('envios.html', transacciones=transacciones)


app/views/historial.py
from flask import Blueprint, render_template
from flask_login import login_required
from app.models import Transacciones

historial = Blueprint('historial', __name__)


@historial.route('/historial')
@login_required
def historial_view():
    transacciones = Transacciones.query.all()
    return render_template('historial.html', transacciones=transacciones)

app/views/inventario.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from app import db
from app.models import Item, Transacciones

inventario = Blueprint('inventario', __name__)


@inventario.route('/inventario')
def inventario_view():
    items = Item.query.all()
    return render_template('inventario.html', items=items)



@inventario.route('/agregar_item', methods=['GET', 'POST'])
@login_required
def agregar_item():
    if request.method == 'POST':
        item_nombre = request.form['nombre']
        dept_id = request.form.get('dept_id')
        cantidad = request.form['cantidad']

        if not item_nombre or not cantidad:
            return "Missing form data", 400

        item = Item.query.filter_by(nombre=item_nombre).first()
        if item:
            item.cantidad += int(cantidad)
            transaccion = Transacciones(item_id=item.item_id, dept_id=1, cantidad_pedida=0, cantidad_entregada=0, cantidad_recibida=int(cantidad), tr_tipo='Recibo', confirmado=True)
        else:
            nuevo_item = Item(nombre=item_nombre, cantidad=int(cantidad))
            db.session.add(nuevo_item)
            db.session.flush()
            transaccion = Transacciones(
                item_id=nuevo_item.item_id,
                dept_id=1,  
                cantidad_pedida=0,
                cantidad_entregada=0,
                cantidad_recibida=cantidad,
                tr_tipo='Recibo',
                confirmado=True
            )
        
        db.session.add(transaccion)
        db.session.commit()
        return redirect(url_for('inventario.inventario_view'))

    return render_template('agregar_item.html')


app/views/pedidos.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app import db, socketio
from app.models import Transacciones, Item, Departamentos, User
from app.tasks import send_notification_email

pedidos = Blueprint('pedidos', __name__)


@pedidos.route('/pedidos', methods = ['GET', 'POST'])
@login_required
def pedidos_view():
    if request.method == 'POST':
        item_id = request.form.get('item_id')
        dept_id = request.form.get('dept_id')
        cantidad_pedida = request.form.get('cantidad_pedida')

        print(f"item_id: {item_id}, dept_id: {dept_id}, cantidad_pedida: {cantidad_pedida}")

        
        if not item_id or not dept_id or not cantidad_pedida:
            return "Missing form data", 400
        
        transaccion = Transacciones(
            item_id=item_id, 
            dept_id=dept_id, 
            cantidad_pedida=cantidad_pedida, 
            tr_tipo='Pedido', 
            pedido_por_id=current_user.user_id
            )
        db.session.add(transaccion)
        db.session.commit()

        
        item = transaccion.related_item
        requester = transaccion.pedido_por_user

        recipients = [user.email for user in User.query.filter(
            User.rol.in_(['admin', 'principal'])
        ).all()]

        # Prepare the email template
        email_template = render_template(
            'email/item_request.html',
            item_name=item.nombre,
            requester_name=requester.nombre
        )

       
        for recipient in recipients:
            send_notification_email(
                to=recipient,
                subject='Nuevo Pedido',
                template=email_template,
                item_name=item.nombre,
                requester_name=requester.nombre
        )
        
        socketio.emit('nuevo_pedido', {'message': 'Se ha hecho un nuevo pedido!'})
        
        return redirect(url_for('inventario.inventario_view'))


    items = Item.query.all()
    departamentos = Departamentos.query.all()
    selected_item_id = request.args.get('item_id')
    selected_dept_id = request.args.get('dept_id')
    return render_template('pedidos.html', items=items, departamentos=departamentos, selected_item_id=selected_item_id, selected_dept_id=selected_dept_id)



app/views/users.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from flask_mail import Message
from app import db, mail, bcrypt, current_app
from app.models import User
from app.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from werkzeug.security import generate_password_hash, check_password_hash

users = Blueprint('users', __name__)


@users.route("/registrar", methods=['GET', 'POST'])
def registrar():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(nombre = form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'\u00a1Tu cuenta ha sido creada, {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('registrar.html', title='Registrar', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('No se pudo iniciar la sesión. Por favor revise su email y contraseña.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))



def send_reset_email(user):
    try:
        token = user.get_reset_token()
        msg = Message('Pedir Cambio de Contraseña',
                      sender='noreply@demo.com',
                      recipients=[user.email])
        msg.body = f'''Para cambiar su contraseña, por favor ingrese al siguiente link:
    {url_for('users.reset_token', token=token, _external=True)}

    Si usted no pidió este cambio, ignore este mensaje y no habrá ninguna alteración.
    '''
        mail.send(msg)
    except Exception as e:
        current_app.logger.error(f"Error sending reset email: {e}")
    raise


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash('Se ha enviado un email con instrucciones para cambiar su contraseña.', 'info')
        else:
            flash('No se encontró una cuenta con ese correo electrónico.', 'warning')
        return redirect(url_for('login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Este token es inválido o ha expirado.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Su contraseña se ha actualizado! Ahora puede iniciar sesión.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


app/templates/agregar_item.html
{% extends "base.html" %}
{% block header_title %}
Agregar/Actualizar Artículo
{% endblock %}

{% block content %}
<div class="ag-container">
    <form action="{{ url_for('inventario.agregar_item') }}" method="POST" class="form">
        <label for="nombre">Nombre del Artículo:</label>
        <input type="text" name="nombre" id="nombre" required />
        <br />
        <label for="cantidad">Ingrese la Cantidad:</label>
        <input type="number" name="cantidad" id="cantidad" required />
        <br />
        <button type="submit">Actualizar</button>
    </form>
</div>

{% endblock content %}

app/templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Gestión de Inventarios</title>
    {% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}" />
    {% endblock %}
    {% block header %}
    {% endblock %}
</head>
<body>
    <header class="header">
        <nav class="navbar">
            <div class="nav-left">
                <a href="{{ url_for('main.index') }}" class="home-button">Home</a>
            </div>
            <div class="nav-title">
                <h1>{% block header_title %}{% endblock %}</h1>
            </div>
            <div class="nav-right">
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('users.logout') }}">Logout</a>
                {% elif request.path not in ['/login', '/registrar'] %}
                <a href="{{ url_for('users.login') }}">Iniciar Sesión</a>
                <a href="{{ url_for('users.registrar') }}">Registrarse</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main role="main" class="msg-container">
        <div class="row">
            <div class="flash-container">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="flash-message alert alert-{{ category }}" style="position: fixed; left: 50%; transform: translate(-50%, -70%);">
                                <p style="text-align: center;">{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </main>
        {% block content %}
        {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/confirmacion.html
{% extends "base.html" %}

{% block header_title %}
Confirmar Pedido
{% endblock %}

{% block content %}

<form action="{{ url_for('confirmacion.confirmacion_view', tr_id=transaccion.tr_id) }}" method="POST">
    <p>Artículo: {{ transaccion.related_item.nombre }}</p>
    <p>Cantidad Pedida: {{ transaccion.cantidad_pedida }}</p>
    <label for="cantidad_entregada">Cantidad Entregada:</label>
    <input type="number" id="cantidad_entregada" name="cantidad_entregada" required>
    <br />
    <button type="submit">Confirmar</button>
</form>

{% endblock content %}

app/templates/confirmaciones.html
{% extends "base.html" %}

{% block header_title %}
Confirmaciones Pendientes
{% endblock %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Usuario</th>
            <th>Artículo</th>
            <th>Cantidad Pedida</th>
            <th>Fecha</th>
            <th>Estatus</th>
        </tr>
    </thead>
    <tbody>
        {% for transaccion in transacciones %}
        <tr>
            <td>{{ transaccion.tr_id }}</td>
            <td>{{ transaccion.pedido_por_user.nombre }}</td>
            <td>{{ transaccion.related_item.nombre }}</td>
            <td>{{ transaccion.cantidad_pedida }}</td>
            <td>{{ transaccion.fecha_pedido.strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>
                <form method="GET" action="{{ url_for('confirmacion.confirmacion_view', tr_id=transaccion.tr_id) }}">
                    <button type="submit">Confirmar Entrega</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/envios.html
{% extends "base.html" %}

{% block header_title %}
Envíos Pendientes
{% endblock %}

{% block header %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.socket.io/4.0.0/socket.io.min.js"></script>
<script>
    $(document).ready(function () {
        var socket = io();

        socket.on('connect', function () {
            console.log('WebSocket connection established.');
        });

        socket.on('nuevo_pedido', function (data) {
            console.log('Received nuevo_pedido event:', data);
            alert(data.message);
            location.reload();
        });

        socket.on('entrega_confirmada', function (data) {
            console.log('Received entrega_confirmada event:', data);
            alert(data.message);
            location.reload();
        });

        socket.on('renotify', function (data) {
            console.log('Received renotify event:', data);
            alert(data.message);
        });
    });
</script>


{% endblock %}

{% block content %}

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Departamento</th>
            <th>Artículo</th>
            <th>Cantidad Pedida</th>
            <th>Fecha</th>
            <th>Estatus</th>
        </tr>
    </thead>
    <tbody>
        {% for transaccion in transacciones %}
        <tr>
            <td>{{ transaccion.tr_id }}</td>
            <td>{{ transaccion.dept_rel.nombre }}</td>
            <td>{{ transaccion.related_item.nombre }}</td>
            <td>{{ transaccion.cantidad_pedida }}</td>
            <td>{{ transaccion.fecha_pedido.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/historial.html
{% extends "base.html" %}

<style>
    .quantity-error {
        background-color: #f8d7da;
        color: #721c24;
    }

        .quantity-error .badge {
            background-color: #f5c6cb;
            color: #721c24;
        }
</style>


{% block header_title %}
Historial de Transacciones
{% endblock %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>Transacción ID</th>
            <th>Usuario</th>
            <th>Artículo</th>
            <th>Departamento</th>
            <th>Cantidad</th>
            <th>Confirmado</th>
            <th>Fecha</th>
        </tr>
    </thead>
    <tbody>
        {% for transaccion in transacciones %}
        <tr>
            <td>{{ transaccion.tr_id }}</td>
            {% if transaccion.tr_tipo == 'Pedido' %}
            <td>{{ transaccion.pedido_por_user.nombre }}</td>
            {% elif transaccion.tr_tipo == 'Entrega' %}
            <td>{{ transaccion.confirmado_por_user.nombre }}</td>
            {% endif %}
            <td>{{ transaccion.related_item.nombre }}</td>
            <td>{{ transaccion.dept_rel.nombre }}</td>
            <td {% if transaccion.has_error %} class="quantity-error" {% endif %}>
                Pedida: {{ transaccion.cantidad_pedida }}<br>
                Entregada: {{ transaccion.cantidad_entregada }}
                <br />
                <br />
                {% if transaccion.cantidad_entregada < transaccion.cantidad_pedida %}
                <span class="badge">Cantidad insuficiente</span>
                {% endif %}
            </td>
            <td>{{ 'Sí' if transaccion.confirmado else 'No' }}</td>
            <td>
                {% if transaccion.confirmado %}
                    {% if transaccion.fecha_confirmado %}
                        Pedido: {{ transaccion.fecha_pedido.strftime('%Y-%m-%d %H:%M:%S') if transaccion.fecha_pedido is not none else '' }}
                        <br />
                        Confirmado: {{ transaccion.fecha_confirmado.strftime('%Y-%m-%d %H:%M:%S') }}
                    {% else %}
                        Pedido: {{ transaccion.fecha_pedido.strftime('%Y-%m-%d %H:%M:%S') if transaccion.fecha_pedido is not none else '' }}
                    {% endif %}
                {% else %}
                    Pedido: {{ transaccion.fecha_pedido.strftime('%Y-%m-%d %H:%M:%S') if transaccion.fecha_pedido is not none else '' }}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/index.html
{% extends "base.html" %}

{% block header_title %}
Bienvenidos a la Gestión de Inventarios
{% endblock %}

{% block content %}

<nav>
    <a href="{{ url_for('inventario.inventario_view') }}">Inventario</a> |
    <a href="{{ url_for('pedidos.pedidos_view') }}">Pedir Artículo</a> |
    <a href="{{ url_for('confirmacion.confirmaciones_view') }}">Confirmar Entrega</a> |
    <a href="{{ url_for('historial.historial_view') }}">Historial de Transacciones</a>|
    <a href="{{ url_for('inventario.agregar_item') }}">Agregar/Actualizar Artículo</a>|
    {% if current_user.is_authenticated and (current_user.rol == 'principal' or current_user.rol == 'admin') %}
    <a href="{{ url_for('envios.envios_view') }}">Envíos Pendientes</a>
    {% endif %}
</nav>

{% endblock content %}

app/templates/inventario.html
{% extends "base.html" %}

{% block header_title %}
Inventario
{% endblock %}

{% block content %}
<table>
    <thead>
        <tr>
            <td>ID</td>
            <td>Artículo</td>
            <td>Cantidad Total</td>
            <td>Acción</td>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.item_id }}</td>
            <td>{{ item.nombre }}</td>
            <td>{{ item.cantidad }}</td>
            <td>
                <form method="GET" action="{{ url_for('pedidos.pedidos_view') }}">
                    <input type="hidden" name="item_id" value="{{ item.item_id }}" />
                    <input type="hidden" name="dept_id" value="1" />
                    <button type="submit">Hacer Pedido</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div>
    <a href="{{ url_for('inventario.agregar_item') }}" class="agregar-button">Agregar/Actualizar Artículo</a>
</div>

{% endblock content %}

app/templates/login.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='auth.css') }}">
{% endblock %}

{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Iniciar Sesión</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request')}}">¿Olvidaste tu contraseña?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        ¿No tienes cuenta? <a class="ml-2" href="{{ url_for('users.registrar') }}">Regístrate Ahora</a>
    </small>
</div>

    {% endblock content %}

app/templates/pedidos.html
{% extends "base.html" %}

{% block header_title %}
Realizar Pedidos
{% endblock %}

{% block content %}
<div class="container">
    <form action="{{ url_for('pedidos.pedidos_view') }}" method="POST" class="pedido-form">
        <label for="item_id">Artículo:</label>
        <select id="item_id" name="item_id" required>
            {% for item in items %}
            <option value="{{ item.item_id }}">{{ item.nombre }}</option>
            {% endfor %}
        </select>

        <label for="dept_id">Departamento:</label>
        <select id="dept_id" name="dept_id" required>
            {% for dept in departamentos %}
            <option value="{{ dept.dept_id }}">{{ dept.nombre }}</option>
            {% endfor %}
        </select>

        <div class="cantidad-center">
            <label for="cantidad_pedida">Cantidad:</label>
            <input type="number" id="cantidad_pedida" name="cantidad_pedida" min="1" required>
        </div>

        <button type="submit">Hacer Pedido</button>
    </form>
</div>

{% endblock content %}

app/templates/registrar.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='auth.css') }}">
{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Registrar</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        ¿Tienes una cuenta? <a class="ml-2" href="{{ url_for('users.login') }}">Iniciar Sesión</a>
    </small>
</div>

    {% endblock content %}

app/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Cambiar Contraseña</legend>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}